### Libraries

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [3]:
train_df= pd.read_csv("/Users/subhashbandaraekanayake/Downloads/DataStrom6.0/damruwan drive/drive-download-20250509T010426Z-001/DataStrom6.0-analyis/train_storming_round.csv")
train_df.head()

,row_id,agent_code,agent_age,agent_join_month,first_policy_sold_month,year_month,unique_proposals_last_7_days,unique_proposals_last_15_days,unique_proposals_last_21_days,unique_proposal,...,unique_quotations,unique_customers_last_7_days,unique_customers_last_15_days,unique_customers_last_21_days,unique_customers,new_policy_count,ANBP_value,net_income,number_of_policy_holders,number_of_cash_payment_policies
0,1,455ca878,45,2/1/2021,9/1/2023,1/1/2023,3,6,2,12,...,9,3,4,8,15,0,0,93313,30,162
1,2,c823ce77,48,4/1/2022,2/1/2024,1/1/2023,1,4,12,21,...,14,4,3,10,17,25,1071450,164804,0,175
2,3,62154055,53,5/1/2020,9/1/2023,1/1/2023,3,5,5,17,...,14,3,7,11,21,26,1601210,426690,84,78
3,4,c58bfa6e,44,7/1/2019,3/1/2022,1/1/2023,1,0,12,17,...,11,2,2,9,13,18,283230,47793,39,144
4,5,b1e5f770,20,9/1/2020,2/1/2023,1/1/2023,0,6,10,17,...,13,3,10,6,19,20,1957680,562239,19,40

In [4]:
print(f"Shape of the dataset: {train_df.shape}")
print(train_df.info())
train_df.describe()

Shape of the dataset: (15308, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15308 entries, 0 to 15307
Data columns (total 23 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   row_id                           15308 non-null  int64
 1   agent_code                       15308 non-null  object
 2   agent_age                        15308 non-null  int64
 3   agent_join_month                 15308 non-null  object
 4   first_policy_sold_month          15308 non-null  object
 5   year_month                       15308 non-null  object
 6   unique_proposals_last_7_days     15308 non-null  int64
 7   unique_proposals_last_15_days    15308 non-null  int64
 8   unique_proposals_last_21_days    15308 non-null  int64
 9   unique_proposal                  15308 non-null  int64
 10  unique_quotations_last_7_days    15308 non-null  int64
 11  unique_quotations_last_15_days   15308 non-null  int64
 12  unique_quotations_last_21_days   15308 non-null  int64
 13  unique_quotations                15308 non-null  int64
 14  unique_customers_last_7_days     15308 non-null  int64
 15  unique_customers_last_15_days    15308 non-null  int64
 16  unique_customers_last_21_days    15308 non-null  int64
 17  unique_customers                 15308 non-null  int64
 18  new_policy_count                 15308 non-null  int64
 19  ANBP_value                       15308 non-null  int64
 20  net_income                       15308 non-null  int64
 21  number_of_policy_holders         15308 non-null  int64
 22  number_of_cash_payment_policies  15308 non-null  int64
dtypes: int64(19), object(4)
memory usage: 2.7+ MB
None

,row_id,agent_age,unique_proposals_last_7_days,unique_proposals_last_15_days,unique_proposals_last_21_days,unique_proposal,unique_quotations_last_7_days,unique_quotations_last_15_days,unique_quotations_last_21_days,unique_quotations,unique_customers_last_7_days,unique_customers_last_15_days,unique_customers_last_21_days,unique_customers,new_policy_count,ANBP_value,net_income,number_of_policy_holders,number_of_cash_payment_policies
count,15308.000000,15308.000000,15308.000000,15308.000000,15308.000000,15308.000000,15308.000000,15308.000000,15308.000000,15308.000000,15308.000000,15308.000000,15308.000000,15308.000000,15308.000000,1.530800e+04,1.530800e+04,15308.000000,15308.000000
mean,7654.500000,40.585772,1.491246,2.991116,10.045728,17.516527,1.989679,2.996538,4.469624,13.922394,2.995493,4.997714,7.500523,15.493729,20.269990,1.025338e+06,2.280414e+05,30.968317,101.180886
std,4419.183296,11.688204,1.119554,2.001613,6.037296,6.616954,1.420996,2.004386,2.875329,4.663777,1.644117,2.438918,3.468597,4.542321,9.541693,8.054989e+05,1.736671e+05,24.621933,75.323464
min,1.000000,20.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000e+00,1.160000e+03,0.000000,0.000000
25%,3827.750000,31.000000,0.000000,1.000000,5.000000,12.000000,1.000000,1.000000,2.000000,11.000000,2.000000,3.000000,5.000000,12.000000,15.000000,3.473238e+05,9.282500e+04,12.000000,38.000000
50%,7654.500000,41.000000,1.000000,3.000000,10.000000,17.000000,2.000000,3.000000,4.000000,14.000000,3.000000,5.000000,8.000000,15.000000,21.000000,9.031445e+05,1.899740e+05,28.000000,90.000000
75%,11481.250000,51.000000,2.000000,5.000000,15.000000,23.000000,3.000000,5.000000,7.000000,17.000000,4.000000,7.000000,10.000000,19.000000,27.000000,1.560700e+06,3.217448e+05,48.000000,152.000000
max,15308.000000,60.000000,3.000000,6.000000,20.000000,34.000000,4.000000,6.000000,9.000000,32.000000,6.000000,10.000000,15.000000,31.000000,42.000000,3.933840e+06,1.140237e+06,116.000000,378.000000

In [5]:
# Convert 'year_month' to datetime if needed
train_df['year_month'] = pd.to_datetime(train_df['year_month'], format='%m/%d/%Y')

# Convert 'agent_join_month' and 'first_policy_sold_month' to datetime (adjusting format if needed)
train_df['agent_join_month'] = pd.to_datetime(train_df['agent_join_month'], format='%m/%d/%Y')
train_df['first_policy_sold_month'] = pd.to_datetime(train_df['first_policy_sold_month'], format='%m/%d/%Y')

# Checking if the conversion is correct
print(train_df[['year_month', 'agent_join_month', 'first_policy_sold_month']].head())

  year_month agent_join_month first_policy_sold_month
0 2023-01-01       2021-02-01              2023-09-01
1 2023-01-01       2022-04-01              2024-02-01
2 2023-01-01       2020-05-01              2023-09-01
3 2023-01-01       2019-07-01              2022-03-01
4 2023-01-01       2020-09-01              2023-02-01

In [6]:
print(train_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15308 entries, 0 to 15307
Data columns (total 23 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   row_id                           15308 non-null  int64
 1   agent_code                       15308 non-null  object
 2   agent_age                        15308 non-null  int64
 3   agent_join_month                 15308 non-null  datetime64[ns]
 4   first_policy_sold_month          15308 non-null  datetime64[ns]
 5   year_month                       15308 non-null  datetime64[ns]
 6   unique_proposals_last_7_days     15308 non-null  int64
 7   unique_proposals_last_15_days    15308 non-null  int64
 8   unique_proposals_last_21_days    15308 non-null  int64
 9   unique_proposal                  15308 non-null  int64
 10  unique_quotations_last_7_days    15308 non-null  int64
 11  unique_quotations_last_15_days   15308 non-null  int64
 12  unique_quotations_last_21_days   15308 non-null  int64
 13  unique_quotations                15308 non-null  int64
 14  unique_customers_last_7_days     15308 non-null  int64
 15  unique_customers_last_15_days    15308 non-null  int64
 16  unique_customers_last_21_days    15308 non-null  int64
 17  unique_customers                 15308 non-null  int64
 18  new_policy_count                 15308 non-null  int64
 19  ANBP_value                       15308 non-null  int64
 20  net_income                       15308 non-null  int64
 21  number_of_policy_holders         15308 non-null  int64
 22  number_of_cash_payment_policies  15308 non-null  int64
dtypes: datetime64[ns](3), int64(19), object(1)
memory usage: 2.7+ MB
None

In [7]:
# Check for missing values
missing_data = train_df.isnull().sum()
missing_percentage = (missing_data / train_df.shape[0]) * 100
print(f"Missing Data Percentage:\n{missing_percentage}")

Missing Data Percentage:
row_id                             0.0
agent_code                         0.0
agent_age                          0.0
agent_join_month                   0.0
first_policy_sold_month            0.0
year_month                         0.0
unique_proposals_last_7_days       0.0
unique_proposals_last_15_days      0.0
unique_proposals_last_21_days      0.0
unique_proposal                    0.0
unique_quotations_last_7_days      0.0
unique_quotations_last_15_days     0.0
unique_quotations_last_21_days     0.0
unique_quotations                  0.0
unique_customers_last_7_days       0.0
unique_customers_last_15_days      0.0
unique_customers_last_21_days      0.0
unique_customers                   0.0
new_policy_count                   0.0
ANBP_value                         0.0
net_income                         0.0
number_of_policy_holders           0.0
number_of_cash_payment_policies    0.0
dtype: float64

In [8]:
from scipy import stats

# Box-Cox transformation (must be applied only on strictly positive values)
train_df['ANBP_value_boxcox_added'], _ = stats.boxcox(train_df['ANBP_value'] + 1)  # Adding 1 to avoid log(0)
train_df['net_income_boxcox_added'], _ = stats.boxcox(train_df['net_income'] + 1)
train_df['number_of_policy_holders_boxcox_added'], _ = stats.boxcox(train_df['number_of_policy_holders'] + 1)
train_df['number_of_cash_payment_policies_boxcox_added'], _ = stats.boxcox(train_df['number_of_cash_payment_policies'] + 1)

### Now lets chaneg the Numarical column in order to New Box-Cox columns

In [9]:
categorical_columns = [
    'agent_code',
    'agent_join_month',
    'first_policy_sold_month',
    'year_month'
]

numerical_columns = [
    'agent_age',
    'unique_proposals_last_7_days',
    'unique_proposals_last_15_days',
    'unique_proposals_last_21_days',
    'unique_proposal',
    'unique_quotations_last_7_days',
    'unique_quotations_last_15_days',
    'unique_quotations_last_21_days',
    'unique_quotations',
    'unique_customers_last_7_days',
    'unique_customers_last_15_days',
    'unique_customers_last_21_days',
    'unique_customers',
    'new_policy_count',
    'ANBP_value_boxcox_added',
    'net_income_boxcox_added',
    'number_of_policy_holders_boxcox_added',
    'number_of_cash_payment_policies_boxcox_added'
]

insted of removing , lets capped

In [10]:
def cap_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_cap = Q1 - 1.5 * IQR
    upper_cap = Q3 + 1.5 * IQR
    df[column] = df[column].clip(lower=lower_cap, upper=upper_cap)
    return df

# Apply capping to each column where outliers are suspected
for column in numerical_columns:
    train_df = cap_outliers(train_df, column)

### Lets do PCA for columsn

In [11]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)

train_df[['pca_quotations_1' ,'pca_quotations_2']] = pca.fit_transform(train_df[['unique_quotations_last_7_days', 'unique_quotations_last_15_days', 'unique_quotations_last_21_days', 'unique_quotations']])
print(train_df[['unique_quotations_last_7_days', 'unique_quotations_last_15_days', 'unique_quotations_last_21_days', 'unique_quotations', 'pca_quotations_1' , 'pca_quotations_2']].head())

   unique_quotations_last_7_days  unique_quotations_last_15_days  \
0                              3                               0
1                              3                               1
2                              1                               6
3                              1                               1
4                              3                               6

   unique_quotations_last_21_days  unique_quotations  pca_quotations_1  \
0                               4                  9         -5.057055
1                               8                 14          1.010476
2                               5                 14          0.544772
3                               5                 11         -2.867246
4                               2                 13         -1.208268

   pca_quotations_2
0          1.619553
1          3.703646
2         -0.286545
3          1.878438
4         -2.928085

In [12]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
train_df[['pca_quotations_1', 'pca_quotations_2']] = scaler.fit_transform(train_df[['pca_quotations_1', 'pca_quotations_2']])
print(train_df[['pca_quotations_1', 'pca_quotations_2']].head())

   pca_quotations_1  pca_quotations_2
0          0.305005          0.683665
1          0.535932          0.828367
2          0.518208          0.551321
3          0.388348          0.701640
4          0.451488          0.367913

### Another data set

In [13]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)

train_df[['pca_customers_1', 'pca_customers_2']] = pca.fit_transform(train_df[['unique_customers_last_7_days', 'unique_customers_last_15_days', 'unique_customers_last_21_days', 'unique_customers']])
print(train_df[['unique_customers_last_7_days', 'unique_customers_last_15_days', 'unique_customers_last_21_days', 'unique_customers', 'pca_customers_1', 'pca_customers_2']].head())

   unique_customers_last_7_days  unique_customers_last_15_days  \
0                             3                              4
1                             4                              3
2                             3                              7
3                             2                              2
4                             3                             10

   unique_customers_last_21_days  unique_customers  pca_customers_1  \
0                              8              15.0        -0.329573
1                             10              17.0         2.263952
2                             11              21.0         6.767039
3                              9              13.0        -1.899018
4                              6              19.0         3.036061

   pca_customers_2
0        -1.157873
1        -2.580617
2         0.513425
3        -3.825496
4         5.410148

### Lets make those values positive using minmaxc scaler , cuz , we are using KNN foir unsupervised leaning

In [14]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
train_df[['pca_customers_1', 'pca_customers_2']] = scaler.fit_transform(train_df[['pca_customers_1', 'pca_customers_2']])
print(train_df[['pca_customers_1', 'pca_customers_2']].head())

   pca_customers_1  pca_customers_2
0         0.488682         0.431759
1         0.566602         0.348196
2         0.701894         0.529921
3         0.441529         0.275080
4         0.589800         0.817523

### For unique Proposal

In [15]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)

train_df[['pca_proposal_1', 'pca_proposal_2']] = pca.fit_transform(train_df[['unique_proposals_last_7_days', 'unique_proposals_last_15_days', 'unique_proposals_last_21_days', 'unique_proposal']])
print(train_df[['unique_proposals_last_7_days', 'unique_proposals_last_15_days', 'unique_proposals_last_21_days', 'unique_proposal', 'pca_proposal_1', 'pca_proposal_2']].head())

   unique_proposals_last_7_days  unique_proposals_last_15_days  \
0                             3                              6
1                             1                              4
2                             3                              5
3                             1                              0
4                             0                              6

   unique_proposals_last_21_days  unique_proposal  pca_proposal_1  \
0                              2               12       -9.333781
1                             12               21        3.928447
2                              5               17       -3.658194
3                             12               17        0.794373
4                             10               17       -0.306078

   pca_proposal_2
0        4.186747
1        1.157052
2        4.048731
3       -3.469136
4        1.818976

In [16]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
train_df[['pca_proposal_1', 'pca_proposal_2']] = scaler.fit_transform(train_df[['pca_proposal_1', 'pca_proposal_2']])
print(train_df[['pca_proposal_1', 'pca_proposal_2']].head())

   pca_proposal_1  pca_proposal_2
0        0.256450        0.842064
1        0.604085        0.593088
2        0.405221        0.830722
3        0.521933        0.212915
4        0.493088        0.647484

In [17]:
categorical_columns = [
    'agent_code',
    'agent_join_month',
    'first_policy_sold_month',
    'year_month'
]

numerical_columns = [
    'agent_age',
    'pca_proposal_1', 
    'pca_proposal_2',
    'pca_quotations_1', 
    'pca_quotations_2', 
    'pca_customers_1',
    'pca_customers_2',
    'new_policy_count',
    'ANBP_value_boxcox_added',
    'net_income_boxcox_added',
    'number_of_policy_holders_boxcox_added',
    'number_of_cash_payment_policies_boxcox_added'
]

### Date Time Processing

In [18]:
# Calculate agent's seniority (in months)
train_df['agent_seniority'] = (train_df['year_month'].dt.year - train_df['agent_join_month'].dt.year) * 12 + \
                              (train_df['year_month'].dt.month - train_df['agent_join_month'].dt.month)

#### This shows that , based on seniority , new policy count dosent change , Not depend on it p value >0.05

In [19]:
# Calculate time to first sale in months
train_df['time_to_first_sale_months'] = (train_df['first_policy_sold_month'].dt.year - train_df['agent_join_month'].dt.year) * 12 + \
                                          (train_df['first_policy_sold_month'].dt.month - train_df['agent_join_month'].dt.month)

print(train_df[['agent_code', 'agent_join_month', 'first_policy_sold_month', 'time_to_first_sale_months']].head())

  agent_code agent_join_month first_policy_sold_month  \
0   455ca878       2021-02-01              2023-09-01
1   c823ce77       2022-04-01              2024-02-01
2   62154055       2020-05-01              2023-09-01
3   c58bfa6e       2019-07-01              2022-03-01
4   b1e5f770       2020-09-01              2023-02-01

   time_to_first_sale_months
0                         31
1                         22
2                         40
3                         32
4                         29

since No outliers

### Lets checek agent perfrormance

In [20]:
# Extract month, quarter, and year from 'year_month'
train_df['month'] = train_df['year_month'].dt.month
train_df['quarter'] = train_df['year_month'].dt.quarter
train_df['year'] = train_df['year_month'].dt.year

In [21]:
from sklearn.preprocessing import LabelEncoder


new_categorical_columns = [
    'agent_code',
    'month',
    'quarter',
    'year',
]


label_encoder = LabelEncoder()

for col in new_categorical_columns:
    train_df[col] = label_encoder.fit_transform(train_df[col])

new_numerical_colsumns = [
    'agent_age',
    'new_policy_count',
    'agent_seniority',
    'time_to_first_sale_months',
    'ANBP_value_boxcox_added',
    'net_income_boxcox_added',
    'number_of_policy_holders_boxcox_added',
    'number_of_cash_payment_policies_boxcox_added',
    'pca_proposal_1', 
    'pca_proposal_2',
    'pca_quotations_1', 
    'pca_quotations_2', 
    'pca_customers_1',
    'pca_customers_2',
]

final_columns = new_categorical_columns + new_numerical_colsumns

In [22]:
train_df[final_columns].to_csv("train_numerical_columns.csv", index=False)